# src/main/resources/application-prod.yml
# Production configuration - uses environment variables from Render

spring:

  cache:
    type: none

  datasource:
    url: ${DATABASE_URL}  # Render will provide this
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 20000
      leak-detection-threshold: 60000

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate  # Never auto-modify in production
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false # This is good. It creates the history table if it doesn't exist.

jwt:
  secret: ${JWT_SECRET}

ai:
  groq:
    api-key: ${GROQ_API_KEY}
  huggingface:
    api-key: ${HUGGINGFACE_API_KEY}
  replicate:
    api-key: ${REPLICATE_API_KEY}
  elevenlabs:
    api-key: ${ELEVENLABS_API_KEY}
  assemblyai:
    api-key: ${ASSEMBLYAI_API_KEY}
  stabilityai:
    api-key: ${STABILITYAI_API_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    com.memorykeeper: INFO
    org.springframework.web: WARN